# Generated by Django 5.2 on 2025-06-01 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
        ('user', '0001_initial'),
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_lat', models.DecimalField(decimal_places=15, max_digits=18)),
                ('from_long', models.DecimalField(decimal_places=15, max_digits=18)),
                ('ambulance_type', models.CharField(max_length=20)),
                ('patient_condition', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=20)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('ambulance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.ambulance')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
